BASE_URL = "https://www.linkedin.com/"
LOGIN_ENDPOINT = "/login?fromSignIn=true&trk=guest_homepage-basic_nav-header-signin"
USER_NAME = "user_email"
USER_PASSWORD = "password"
SEARCH_INPUT = "Add linkedin friend"
